version: '2'
services:
    jhipster_react_sample_app-app:
        image: jhipster_react_sample_app
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster_react_sample_app-mysql:3306/jhipster_react_sample_app?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster_react_sample_app-mysql:
        extends:
            file: mysql.yml
            service: jhipster_react_sample_app-mysql
